export const FETCH_MOVIES_LIST_START = "FETCH_MOVIES_LIST_START";
export const FETCH_MOVIES_LIST_SUCCESS = "FETCH_MOVIES_LIST_SUCCESS";
export const FETCH_MOVIES_LIST_FAILURE = "FETCH_MOVIES_LIST_FAILURE";

export const CRAWL_MOVIE_START = "CRAWL_MOVIES_START";
export const CRAWL_MOVIES_SUCCESS = "CRAWL_MOVIES_SUCCESS";
export const CRAWL_MOVIES_FAILURE = "CRAWL_MOVIES_FAILURE";
