export const FETCH_TUTORIALS_START = "FETCH_TUTORIALS_START";
export const FETCH_TUTORIALS_SUCCESS = "FETCH_TUTORIALS_SUCCESS";
export const FETCH_TUTORIALS_FAILURE = "FETCH_TUTORIALS_FAILURE";

export const FETCH_ONE_TUTORIAL_START = "FETCH_ONE_TUTORIAL_START";
export const FETCH_ONE_TUTORIAL_SUCCESS = "FETCH_ONE_TUTORIAL_SUCCESS";
export const FETCH_ONE_TUTORIAL_FAILURE = "FETCH_ONE_TUTORIAL_FAILURE";

export const DELETE_TUTORIAL_START = "DELETE_TUTORIAL_START";
export const DELETE_TUTORIAL_SUCCESS = "DELETE_TUTORIAL_SUCCESS";
export const DELETE_TUTORIAL_FAILURE = "DELETE_TUTORIAL_FAILURE";

export const CLEAR_TUTORIAL = "CLEAR_TUTORIAL";
export const CLEAR_ERRORS_AND_LINK = "CLEAR_ERRORS_AND_LINK";

export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const CREATE_TUTORIAL_START = "CREATE_TUTORIAL_START";
export const CREATE_TUTORIAL_SUCCESS = "CREATE_TUTORIAL_SUCCESS";
export const CREATE_TUTORIAL_FAILURE = "CREATE_TUTORIAL_FAILURE";

export const UPDATE_TUTORIAL_START = "UPDATE_TUTORIAL_START";
export const UPDATE_TUTORIAL_SUCCESS = "UPDATE_TUTORIAL_SUCCESS";
export const UPDATE_TUTORIAL_FAILURE = "UPDATE_TUTORIAL_FAILURE";
