export const FETCH_TUTORIALS_START = "FETCH_TUTORIALS_START";
export const FETCH_TUTORIALS_SUCCESS = "FETCH_TUTORIALS_SUCCESS";
export const FETCH_TUTORIALS_FAILURE = "FETCH_TUTORIALS_FAILURE";
export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";
