export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SET_USER_START = "SET_USER_START";

export const SIGN_OUT_START = "SIGN_OUT_START";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const SAVE_TUTORIAL_START = "SAVE_TUTORIAL_START";
export const SAVE_TUTORIAL_SUCCESS = "SAVE_TUTORIAL_SUCCESS";
export const SAVE_TUTORIAL_FAILURE = "SAVE_TUTORIAL_FAILURE";

export const SEARCH_USER_START = "SEARCH_USER_START";
export const SEARCH_USER_SUCCESS = "SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE = "SEARCH_USER_FAILURE";

export const CREATE_MENTOR_START = "CREATE_MENTOR_START";
export const CREATE_MENTOR_SUCCESS = "CREATE_MENTOR_SUCCESS";
export const CREATE_MENTOR_FAILURE = "CREATE_MENTOR_FAILURE";

export const GET_MENTORS_START = "GET_MENTORS_START";
export const GET_MENTORS_SUCCESS = "GET_MENTORS_SUCCESS";
export const GET_MENTORS_FAILURE = "GET_MENTORS_FAILURE";

export const DELETE_MENTOR_START = "DELETE_MENTOR_START";
export const DELETE_MENTOR_SUCCESS = "DELETE_MENTOR_SUCCESS";
export const DELETE_MENTOR_FAILURE = "DELETE_MENTOR_FAILURE";

export const UPDATE_ACTIVE_OF_MENTOR_START = "UPDATE_ACTIVE_OF_MENTOR_START";
export const UPDATE_ACTIVE_OF_MENTOR_SUCCESS = "UPDATE_ACTIVE_OF_MENTOR_SUCCESS";
export const UPDATE_ACTIVE_OF_MENTOR_FAILURE = "UPDATE_ACTIVE_OF_MENTOR_FAILURE";
