export const SIGN_UP_START = "SIGN_UP_START";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";

export const SET_USER_START = "SET_USER_START";

export const SIGN_OUT_START = "SIGN_OUT_START";

export const SIGN_IN_START = "SIGN_IN_START";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const GET_SAVED_TUTORIALS_START = "GET_SAVED_TUTORIALS_START";
export const GET_SAVED_TUTORIALS_SUCCESS = "GET_SAVED_TUTORIALS_SUCCESS";
export const GET_SAVED_TUTORIALS_FAILURE = "GET_SAVED_TUTORIALS_FAILURE";

export const SAVE_TUTORIAL_START = "SAVE_TUTORIAL_START";
export const SAVE_TUTORIAL_SUCCESS = "SAVE_TUTORIAL_SUCCESS";
export const SAVE_TUTORIAL_FAILURE = "SAVE_TUTORIAL_FAILURE";
