export const FETCH_NEWS_LIST_START = "FETCH_NEWS_LIST_START";
export const FETCH_NEWS_LIST_SUCCESS = "FETCH_NEWS_LIST_SUCCESS";
export const FETCH_NEWS_LIST_FAILURE = "FETCH_NEWS_LIST_FAILURE";

export const FETCH_NEWS_START = "FETCH_NEWS_START";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";

export const DELETE_NEWS_START = "DELETE_NEWS_START";
export const DELETE_NEWS_SUCCESS = "DELETE_NEWS_SUCCESS";
export const DELETE_NEWS_FAILURE = "DELETE_NEWS_FAILURE";

export const CLEAR_NEWS = "CLEAR_NEWS";
export const CLEAR_NEWS_LIST = "CLEAR_NEWS_LIST";
export const CLEAR_ERRORS_AND_LINK = "CLEAR_ERRORS_AND_LINK";

export const UPLOAD_IMAGE_START = "UPLOAD_IMAGE_START";
export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";
export const UPLOAD_IMAGE_FAILURE = "UPLOAD_IMAGE_FAILURE";

export const CREATE_NEWS_START = "CREATE_NEWS_START";
export const CREATE_NEWS_SUCCESS = "CREATE_NEWS_SUCCESS";
export const CREATE_NEWS_FAILURE = "CREATE_NEWS_FAILURE";

export const UPDATE_NEWS_START = "UPDATE_NEWS_START";
export const UPDATE_NEWS_SUCCESS = "UPDATE_NEWS_SUCCESS";
export const UPDATE_NEWS_FAILURE = "UPDATE_NEWS_FAILURE";

export const SEARCH_NEWS_LIST_START = "SEARCH_NEWS_LIST_START";
export const SEARCH_NEWS_LIST_SUCCESS = "SEARCH_NEWS_LIST_SUCCESS";
export const SEARCH_NEWS_LIST_FAILURE = "SEARCH_NEWS_LIST_FAILURE";
